#!/bin/bash
set -x
wget 'http://www2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_32_tract_500k.zip'
unzip -o cb_2014_32_tract_500k.zip
shp2json cb_2014_32_tract_500k.shp -o nv.json
# Taken from d3-stateplane
# https://github.com/veltman/d3-stateplane (Nevada Central)

# geoproject 'd3.geoTransverseMercator().rotate([116 + 40 / 60, -34 - 45 / 60]).fitSize([960, 960], d)' < nv.json > nv-merc.json
geoproject 'd3.geoTransverseMercator().rotate([116 + 40 / 60, -34 - 45 / 60]).fitExtent([[10, 10], [950, 1090]], d)' < nv.json > nv-merc.json
geoproject  'd3.geoMercator().center([-122.433701, 37.767683]).scale(25000).translate([960/2, 500/2])' < Bay_Area.json >Bay_Area-merc.json
ndjson-split 'd.features'  < nv-merc.json  > nv-merc.ndjson
ndjson-map 'd.id = d.properties.GEOID.slice(2), d' < nv-merc.ndjson > nv-merc-id.ndjson
wget -O cb_2014_32_tract_B01003.json 'http://api.census.gov/data/2014/acs5?get=B01003_001E&for=tract:*&in=state:32'
ndjson-cat cb_2014_32_tract_B01003.json | ndjson-split 'd.slice(1)' | ndjson-map '{id: d[2] + d[3], B01003: +d[0]}'  > cb_2014_32_tract_B01003.ndjson

ndjson-join 'd.id' nv-merc-id.ndjson cb_2014_32_tract_B01003.ndjson > nv-merc-join.ndjson

ndjson-map 'd[0].properties = {density: Math.floor(d[1].B01003 / d[0].properties.ALAND * 2589975.2356)}, d[0]' < nv-merc-join.ndjson > nv-merc-density.ndjson
geo2topo -n tracts=nv-merc-density.ndjson > nv-tracts-topo.json
toposimplify -p 1 -f < nv-tracts-topo.json > nv-simple-topo.json
topoquantize 1e5 < nv-simple-topo.json > nv-quantized-topo.json
topomerge -k 'd.id.slice(0, 3)' counties=tracts < nv-quantized-topo.json > nv-merge-topo.json
topomerge --mesh -f 'a !== b' counties=counties < nv-merge-topo.json > nv-topo.json

# State boundries
topomerge --mesh -f 'a == b' counties=counties < nv-merge-topo.json > nv-state-topo.json



# Step 1 . Convert shp file to ndjson
ndjson-cat Bay_Area.json| ndjson-split 'd.features' >Bay_Area.ndjson

# Convert GEOID10 to Zip
ndjson-map 'd.Zip = d.properties.GEOID10, d' < Bay_Area.ndjson >Bay_Area-id.ndjson

#Convert zip data from csv to json
csvtojson MedianZIP-3-csv.csv > MedianZip-3.json
# Convert zip data to ndjson
ndjson-cat MedianZip-3.json > MedianZip-3.ndjson
# Process ndjson
ndjson-cat MedianZip-3.ndjson| ndjson-split 'd.slice(1)' > Median-Zip-3-proc.ndjson

# Join Income data to Map
ndjson-join 'd.Zip' Bay_Area-id.ndjson Median-Zip-3-proc.ndjson > Bay_Area_Income_proc.ndjson
# ndjson-map 'Object.assign(d[0], d[1])' <Bay_Area_Income_proc.ndjson > Bay_Area_Income.ndjson

ndjson-map 'd[0].properties = {Income: d[1].Median, Pop: d[1].Pop, Zip: d[1].Zip}, d[0]' < Bay_Area_Income_proc.ndjson > Bay_Area_Income2.ndjson


csvtojson Rental-1-zip-csv.csv > Rental-1-zip.json

ndjson-cat Rental-1-zip.json > Rental-1-zip.ndjson
ndjson-cat Rental-1-zip.ndjson | ndjson-split  'd.slice(1)' > Rental-1-zip-proc.ndjson

ndjson-join 'd.Zip' Median-Zip-3-proc.ndjson Rental-1-zip-proc.ndjson > test

